#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0.2 effective-5.10 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
#ifndef IDENTITYFRAUD_SWIFT_H
#define IDENTITYFRAUD_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="IdentityFraud",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSString;

SWIFT_CLASS("_TtC13IdentityFraud12AppAnalytics")
@interface AppAnalytics : NSObject
@property (nonatomic, copy) NSDictionary<NSString *, NSNumber *> * _Nullable affinity;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13IdentityFraud10DeviceMeta")
@interface DeviceMeta : NSObject
@property (nonatomic, copy) NSString * _Nullable cpuType;
@property (nonatomic, copy) NSString * _Nullable product;
@property (nonatomic, copy) NSString * _Nullable androidVersion;
@property (nonatomic, copy) NSString * _Nullable iOSVersion;
@property (nonatomic, copy) NSString * _Nullable storageAvailable;
@property (nonatomic, copy) NSString * _Nullable storageTotal;
@property (nonatomic, copy) NSString * _Nullable model;
@property (nonatomic, copy) NSString * _Nullable screenResolution;
@property (nonatomic, copy) NSString * _Nullable brand;
@property (nonatomic, copy) NSString * _Nullable totalRAM;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, Environment, open) {
  EnvironmentDEV = 0,
  EnvironmentSTAGING = 1,
  EnvironmentPROD = 2,
};

@class NSNumber;

SWIFT_CLASS("_TtC13IdentityFraud11GPSLocation")
@interface GPSLocation : NSObject
@property (nonatomic, strong) NSNumber * _Nullable latitude;
@property (nonatomic, strong) NSNumber * _Nullable longitude;
@property (nonatomic, strong) NSNumber * _Nullable altitude;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLatitude:(double)latitude longitude:(double)longitude altitude:(double)altitude OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13IdentityFraud9IPDetails")
@interface IPDetails : NSObject
@property (nonatomic, copy) NSString * _Nullable asn;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable country;
@property (nonatomic, copy) NSString * _Nullable isp;
@property (nonatomic, copy) NSString * _Nullable region;
@property (nonatomic, strong) NSNumber * _Nullable fraudScore;
@property (nonatomic, strong) NSNumber * _Nullable latitude;
@property (nonatomic, strong) NSNumber * _Nullable longitude;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class Options;
@class UpdateOption;
@protocol IntelligenceResponseListener;
@class UIViewController;

SWIFT_CLASS("_TtC13IdentityFraud11IdentitySDK")
@interface IdentitySDK : NSObject
+ (IdentitySDK * _Nonnull)getInstance SWIFT_WARN_UNUSED_RESULT SWIFT_AVAILABILITY(ios,introduced=15.0);
- (void)initAsyncWithOptions:(Options * _Nonnull)options completion:(void (^ _Nonnull)(BOOL))completion SWIFT_METHOD_FAMILY(none) SWIFT_AVAILABILITY(ios,introduced=15.0);
- (void)updateOptionsWithUpdateOption:(UpdateOption * _Nonnull)updateOption SWIFT_AVAILABILITY(ios,introduced=15.0);
- (void)getIntelligenceWithListener:(id <IntelligenceResponseListener> _Nonnull)listener SWIFT_AVAILABILITY(ios,introduced=15.0);
- (NSString * _Nonnull)getSessionId SWIFT_WARN_UNUSED_RESULT SWIFT_AVAILABILITY(ios,introduced=15.0);
- (void)protectScreenCapture:(UIViewController * _Nonnull)viewController SWIFT_AVAILABILITY(ios,introduced=15.0);
- (void)stopScreenCaptureProtection:(UIViewController * _Nonnull)viewController SWIFT_AVAILABILITY(ios,introduced=15.0);
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13IdentityFraud17IntelligenceError")
@interface IntelligenceError : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull requestId;
@property (nonatomic, readonly, copy) NSString * _Nonnull errorMessage;
- (nonnull instancetype)initWithRequestId:(NSString * _Nonnull)requestId errorMessage:(NSString * _Nonnull)errorMessage OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13IdentityFraud20IntelligenceResponse")
@interface IntelligenceResponse : NSObject
@property (nonatomic, copy) NSString * _Nullable sessionId;
@property (nonatomic, readonly, copy) NSString * _Nullable deviceId;
@property (nonatomic, readonly, copy) NSString * _Nullable requestId;
@property (nonatomic, strong) NSNumber * _Nullable simulator;
@property (nonatomic, strong) NSNumber * _Nullable jailbroken;
@property (nonatomic, strong) NSNumber * _Nullable vpn;
@property (nonatomic, strong) NSNumber * _Nullable geoSpoofed;
@property (nonatomic, strong) NSNumber * _Nullable appTampering;
@property (nonatomic, strong) NSNumber * _Nullable hooking;
@property (nonatomic, strong) NSNumber * _Nullable proxy;
@property (nonatomic, strong) NSNumber * _Nullable mirroredScreen;
@property (nonatomic, strong) GPSLocation * _Nullable gpsLocation;
@property (nonatomic, strong) NSNumber * _Nullable cloned;
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nullable additionalData;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable clientUserIds;
@property (nonatomic, strong) NSNumber * _Nullable newDevice;
@property (nonatomic, copy) NSString * _Nullable ip;
@property (nonatomic, strong) IPDetails * _Nullable ipDetails;
@property (nonatomic, strong) NSNumber * _Nullable factoryReset;
@property (nonatomic, strong) NSNumber * _Nullable deviceRiskScore;
@property (nonatomic, strong) NSNumber * _Nullable sessionRiskScore;
@property (nonatomic, strong) NSNumber * _Nullable factoryResetTime;
@property (nonatomic, strong) DeviceMeta * _Nullable deviceMeta;
@property (nonatomic, strong) AppAnalytics * _Nullable appAnalytics;
- (nonnull instancetype)initWithSessionId:(NSString * _Nullable)sessionId deviceId:(NSString * _Nullable)deviceId requestId:(NSString * _Nullable)requestId simulator:(BOOL)simulator jailbroken:(BOOL)jailbroken vpn:(BOOL)vpn geoSpoofed:(BOOL)geoSpoofed appTampering:(BOOL)appTampering hooking:(BOOL)hooking proxy:(BOOL)proxy mirroredScreen:(BOOL)mirroredScreen gpsLocation:(GPSLocation * _Nullable)gpsLocation cloned:(BOOL)cloned clientUserIds:(NSArray<NSString *> * _Nullable)clientUserIds newDevice:(BOOL)newDevice ip:(NSString * _Nullable)ip ipDetails:(IPDetails * _Nullable)ipDetails factoryReset:(BOOL)factoryReset deviceRiskScore:(float)deviceRiskScore sessionRiskScore:(float)sessionRiskScore factoryResetTime:(int64_t)factoryResetTime deviceMeta:(DeviceMeta * _Nullable)deviceMeta appAnalytics:(AppAnalytics * _Nullable)appAnalytics OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP13IdentityFraud28IntelligenceResponseListener_")
@protocol IntelligenceResponseListener
- (void)onSuccessWithResponse:(IntelligenceResponse * _Nonnull)response;
- (void)onErrorWithError:(IntelligenceError * _Nonnull)error;
@end

@class OptionBuilder;

SWIFT_CLASS("_TtC13IdentityFraud7Options")
@interface Options : NSObject
- (OptionBuilder * _Nonnull)toBuilder SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum PhoneInputType : NSInteger;
enum OtpInputType : NSInteger;
enum UserEventType : NSInteger;

SWIFT_CLASS("_TtCC13IdentityFraud7Options13OptionBuilder")
@interface OptionBuilder : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (OptionBuilder * _Nonnull)setClientId:(NSString * _Nonnull)clientId SWIFT_WARN_UNUSED_RESULT;
- (OptionBuilder * _Nonnull)setClientSecret:(NSString * _Nonnull)clientSecret SWIFT_WARN_UNUSED_RESULT;
- (OptionBuilder * _Nonnull)setBaseUrl:(NSString * _Nullable)url SWIFT_WARN_UNUSED_RESULT;
- (OptionBuilder * _Nonnull)setEnvironment:(enum Environment)environment SWIFT_WARN_UNUSED_RESULT;
- (OptionBuilder * _Nonnull)setPhoneNumber:(NSString * _Nullable)phoneNumber SWIFT_WARN_UNUSED_RESULT;
- (OptionBuilder * _Nonnull)setPhoneInputType:(enum PhoneInputType)phoneInputType SWIFT_WARN_UNUSED_RESULT;
- (OptionBuilder * _Nonnull)setOtpInputType:(enum OtpInputType)otpInputType SWIFT_WARN_UNUSED_RESULT;
- (OptionBuilder * _Nonnull)setUserId:(NSString * _Nullable)userId SWIFT_WARN_UNUSED_RESULT;
- (OptionBuilder * _Nonnull)setUserEventType:(enum UserEventType)userEventType SWIFT_WARN_UNUSED_RESULT;
- (OptionBuilder * _Nonnull)setMerchantId:(NSString * _Nullable)merchantId SWIFT_WARN_UNUSED_RESULT;
- (OptionBuilder * _Nonnull)setAdditionalAttributes:(NSDictionary<NSString *, NSString *> * _Nonnull)additionalAttributes SWIFT_WARN_UNUSED_RESULT;
- (Options * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, OtpInputType, open) {
  OtpInputTypeMANUAL = 0,
  OtpInputTypeCOPY_PASTED = 1,
  OtpInputTypeAUTO_FILLED = 2,
};

typedef SWIFT_ENUM(NSInteger, PhoneInputType, open) {
  PhoneInputTypeMANUAL = 0,
  PhoneInputTypeCOPY_PASTE = 1,
  PhoneInputTypeGOOGLE_HINT = 2,
};


SWIFT_CLASS("_TtC13IdentityFraud12UpdateOption")
@interface UpdateOption : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC13IdentityFraud12UpdateOption19UpdateOptionBuilder")
@interface UpdateOptionBuilder : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (UpdateOptionBuilder * _Nonnull)setPhoneNumber:(NSString * _Nullable)phoneNumber SWIFT_WARN_UNUSED_RESULT;
- (UpdateOptionBuilder * _Nonnull)setPhoneInputType:(enum PhoneInputType)phoneInputType SWIFT_WARN_UNUSED_RESULT;
- (UpdateOptionBuilder * _Nonnull)setOtpInputType:(enum OtpInputType)otpInputType SWIFT_WARN_UNUSED_RESULT;
- (UpdateOptionBuilder * _Nonnull)setUserId:(NSString * _Nullable)userId SWIFT_WARN_UNUSED_RESULT;
- (UpdateOptionBuilder * _Nonnull)setUserEventType:(enum UserEventType)userEventType SWIFT_WARN_UNUSED_RESULT;
- (UpdateOptionBuilder * _Nonnull)setMerchantId:(NSString * _Nullable)merchantId SWIFT_WARN_UNUSED_RESULT;
- (UpdateOptionBuilder * _Nonnull)setAdditionalAttributes:(NSDictionary<NSString *, NSString *> * _Nonnull)additionalAttributes SWIFT_WARN_UNUSED_RESULT;
- (UpdateOption * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, UserEventType, open) {
  UserEventTypeLOGIN = 0,
  UserEventTypeSIGNUP = 1,
  UserEventTypeTRANSACTION = 2,
  UserEventTypeOTHERS = 3,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.0.2 effective-5.10 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
#ifndef IDENTITYFRAUD_SWIFT_H
#define IDENTITYFRAUD_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="IdentityFraud",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSString;

SWIFT_CLASS("_TtC13IdentityFraud12AppAnalytics")
@interface AppAnalytics : NSObject
@property (nonatomic, copy) NSDictionary<NSString *, NSNumber *> * _Nullable affinity;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13IdentityFraud10DeviceMeta")
@interface DeviceMeta : NSObject
@property (nonatomic, copy) NSString * _Nullable cpuType;
@property (nonatomic, copy) NSString * _Nullable product;
@property (nonatomic, copy) NSString * _Nullable androidVersion;
@property (nonatomic, copy) NSString * _Nullable iOSVersion;
@property (nonatomic, copy) NSString * _Nullable storageAvailable;
@property (nonatomic, copy) NSString * _Nullable storageTotal;
@property (nonatomic, copy) NSString * _Nullable model;
@property (nonatomic, copy) NSString * _Nullable screenResolution;
@property (nonatomic, copy) NSString * _Nullable brand;
@property (nonatomic, copy) NSString * _Nullable totalRAM;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, Environment, open) {
  EnvironmentDEV = 0,
  EnvironmentSTAGING = 1,
  EnvironmentPROD = 2,
};

@class NSNumber;

SWIFT_CLASS("_TtC13IdentityFraud11GPSLocation")
@interface GPSLocation : NSObject
@property (nonatomic, strong) NSNumber * _Nullable latitude;
@property (nonatomic, strong) NSNumber * _Nullable longitude;
@property (nonatomic, strong) NSNumber * _Nullable altitude;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLatitude:(double)latitude longitude:(double)longitude altitude:(double)altitude OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13IdentityFraud9IPDetails")
@interface IPDetails : NSObject
@property (nonatomic, copy) NSString * _Nullable asn;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable country;
@property (nonatomic, copy) NSString * _Nullable isp;
@property (nonatomic, copy) NSString * _Nullable region;
@property (nonatomic, strong) NSNumber * _Nullable fraudScore;
@property (nonatomic, strong) NSNumber * _Nullable latitude;
@property (nonatomic, strong) NSNumber * _Nullable longitude;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class Options;
@class UpdateOption;
@protocol IntelligenceResponseListener;
@class UIViewController;

SWIFT_CLASS("_TtC13IdentityFraud11IdentitySDK")
@interface IdentitySDK : NSObject
+ (IdentitySDK * _Nonnull)getInstance SWIFT_WARN_UNUSED_RESULT SWIFT_AVAILABILITY(ios,introduced=15.0);
- (void)initAsyncWithOptions:(Options * _Nonnull)options completion:(void (^ _Nonnull)(BOOL))completion SWIFT_METHOD_FAMILY(none) SWIFT_AVAILABILITY(ios,introduced=15.0);
- (void)updateOptionsWithUpdateOption:(UpdateOption * _Nonnull)updateOption SWIFT_AVAILABILITY(ios,introduced=15.0);
- (void)getIntelligenceWithListener:(id <IntelligenceResponseListener> _Nonnull)listener SWIFT_AVAILABILITY(ios,introduced=15.0);
- (NSString * _Nonnull)getSessionId SWIFT_WARN_UNUSED_RESULT SWIFT_AVAILABILITY(ios,introduced=15.0);
- (void)protectScreenCapture:(UIViewController * _Nonnull)viewController SWIFT_AVAILABILITY(ios,introduced=15.0);
- (void)stopScreenCaptureProtection:(UIViewController * _Nonnull)viewController SWIFT_AVAILABILITY(ios,introduced=15.0);
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13IdentityFraud17IntelligenceError")
@interface IntelligenceError : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull requestId;
@property (nonatomic, readonly, copy) NSString * _Nonnull errorMessage;
- (nonnull instancetype)initWithRequestId:(NSString * _Nonnull)requestId errorMessage:(NSString * _Nonnull)errorMessage OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13IdentityFraud20IntelligenceResponse")
@interface IntelligenceResponse : NSObject
@property (nonatomic, copy) NSString * _Nullable sessionId;
@property (nonatomic, readonly, copy) NSString * _Nullable deviceId;
@property (nonatomic, readonly, copy) NSString * _Nullable requestId;
@property (nonatomic, strong) NSNumber * _Nullable simulator;
@property (nonatomic, strong) NSNumber * _Nullable jailbroken;
@property (nonatomic, strong) NSNumber * _Nullable vpn;
@property (nonatomic, strong) NSNumber * _Nullable geoSpoofed;
@property (nonatomic, strong) NSNumber * _Nullable appTampering;
@property (nonatomic, strong) NSNumber * _Nullable hooking;
@property (nonatomic, strong) NSNumber * _Nullable proxy;
@property (nonatomic, strong) NSNumber * _Nullable mirroredScreen;
@property (nonatomic, strong) GPSLocation * _Nullable gpsLocation;
@property (nonatomic, strong) NSNumber * _Nullable cloned;
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nullable additionalData;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable clientUserIds;
@property (nonatomic, strong) NSNumber * _Nullable newDevice;
@property (nonatomic, copy) NSString * _Nullable ip;
@property (nonatomic, strong) IPDetails * _Nullable ipDetails;
@property (nonatomic, strong) NSNumber * _Nullable factoryReset;
@property (nonatomic, strong) NSNumber * _Nullable deviceRiskScore;
@property (nonatomic, strong) NSNumber * _Nullable sessionRiskScore;
@property (nonatomic, strong) NSNumber * _Nullable factoryResetTime;
@property (nonatomic, strong) DeviceMeta * _Nullable deviceMeta;
@property (nonatomic, strong) AppAnalytics * _Nullable appAnalytics;
- (nonnull instancetype)initWithSessionId:(NSString * _Nullable)sessionId deviceId:(NSString * _Nullable)deviceId requestId:(NSString * _Nullable)requestId simulator:(BOOL)simulator jailbroken:(BOOL)jailbroken vpn:(BOOL)vpn geoSpoofed:(BOOL)geoSpoofed appTampering:(BOOL)appTampering hooking:(BOOL)hooking proxy:(BOOL)proxy mirroredScreen:(BOOL)mirroredScreen gpsLocation:(GPSLocation * _Nullable)gpsLocation cloned:(BOOL)cloned clientUserIds:(NSArray<NSString *> * _Nullable)clientUserIds newDevice:(BOOL)newDevice ip:(NSString * _Nullable)ip ipDetails:(IPDetails * _Nullable)ipDetails factoryReset:(BOOL)factoryReset deviceRiskScore:(float)deviceRiskScore sessionRiskScore:(float)sessionRiskScore factoryResetTime:(int64_t)factoryResetTime deviceMeta:(DeviceMeta * _Nullable)deviceMeta appAnalytics:(AppAnalytics * _Nullable)appAnalytics OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP13IdentityFraud28IntelligenceResponseListener_")
@protocol IntelligenceResponseListener
- (void)onSuccessWithResponse:(IntelligenceResponse * _Nonnull)response;
- (void)onErrorWithError:(IntelligenceError * _Nonnull)error;
@end

@class OptionBuilder;

SWIFT_CLASS("_TtC13IdentityFraud7Options")
@interface Options : NSObject
- (OptionBuilder * _Nonnull)toBuilder SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum PhoneInputType : NSInteger;
enum OtpInputType : NSInteger;
enum UserEventType : NSInteger;

SWIFT_CLASS("_TtCC13IdentityFraud7Options13OptionBuilder")
@interface OptionBuilder : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (OptionBuilder * _Nonnull)setClientId:(NSString * _Nonnull)clientId SWIFT_WARN_UNUSED_RESULT;
- (OptionBuilder * _Nonnull)setClientSecret:(NSString * _Nonnull)clientSecret SWIFT_WARN_UNUSED_RESULT;
- (OptionBuilder * _Nonnull)setBaseUrl:(NSString * _Nullable)url SWIFT_WARN_UNUSED_RESULT;
- (OptionBuilder * _Nonnull)setEnvironment:(enum Environment)environment SWIFT_WARN_UNUSED_RESULT;
- (OptionBuilder * _Nonnull)setPhoneNumber:(NSString * _Nullable)phoneNumber SWIFT_WARN_UNUSED_RESULT;
- (OptionBuilder * _Nonnull)setPhoneInputType:(enum PhoneInputType)phoneInputType SWIFT_WARN_UNUSED_RESULT;
- (OptionBuilder * _Nonnull)setOtpInputType:(enum OtpInputType)otpInputType SWIFT_WARN_UNUSED_RESULT;
- (OptionBuilder * _Nonnull)setUserId:(NSString * _Nullable)userId SWIFT_WARN_UNUSED_RESULT;
- (OptionBuilder * _Nonnull)setUserEventType:(enum UserEventType)userEventType SWIFT_WARN_UNUSED_RESULT;
- (OptionBuilder * _Nonnull)setMerchantId:(NSString * _Nullable)merchantId SWIFT_WARN_UNUSED_RESULT;
- (OptionBuilder * _Nonnull)setAdditionalAttributes:(NSDictionary<NSString *, NSString *> * _Nonnull)additionalAttributes SWIFT_WARN_UNUSED_RESULT;
- (Options * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, OtpInputType, open) {
  OtpInputTypeMANUAL = 0,
  OtpInputTypeCOPY_PASTED = 1,
  OtpInputTypeAUTO_FILLED = 2,
};

typedef SWIFT_ENUM(NSInteger, PhoneInputType, open) {
  PhoneInputTypeMANUAL = 0,
  PhoneInputTypeCOPY_PASTE = 1,
  PhoneInputTypeGOOGLE_HINT = 2,
};


SWIFT_CLASS("_TtC13IdentityFraud12UpdateOption")
@interface UpdateOption : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC13IdentityFraud12UpdateOption19UpdateOptionBuilder")
@interface UpdateOptionBuilder : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (UpdateOptionBuilder * _Nonnull)setPhoneNumber:(NSString * _Nullable)phoneNumber SWIFT_WARN_UNUSED_RESULT;
- (UpdateOptionBuilder * _Nonnull)setPhoneInputType:(enum PhoneInputType)phoneInputType SWIFT_WARN_UNUSED_RESULT;
- (UpdateOptionBuilder * _Nonnull)setOtpInputType:(enum OtpInputType)otpInputType SWIFT_WARN_UNUSED_RESULT;
- (UpdateOptionBuilder * _Nonnull)setUserId:(NSString * _Nullable)userId SWIFT_WARN_UNUSED_RESULT;
- (UpdateOptionBuilder * _Nonnull)setUserEventType:(enum UserEventType)userEventType SWIFT_WARN_UNUSED_RESULT;
- (UpdateOptionBuilder * _Nonnull)setMerchantId:(NSString * _Nullable)merchantId SWIFT_WARN_UNUSED_RESULT;
- (UpdateOptionBuilder * _Nonnull)setAdditionalAttributes:(NSDictionary<NSString *, NSString *> * _Nonnull)additionalAttributes SWIFT_WARN_UNUSED_RESULT;
- (UpdateOption * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, UserEventType, open) {
  UserEventTypeLOGIN = 0,
  UserEventTypeSIGNUP = 1,
  UserEventTypeTRANSACTION = 2,
  UserEventTypeOTHERS = 3,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
